### ISSUE TITLE
I can't claim my own gravestone

### ISSUE THREAD

**Issue by CaioMS2000** [PneumonoIsNotAvailable/Gravestones#12]
I died and i can't claim my own gravestone, i used the "/gavestone getdata player" command to prove that is mine.
![image](https://github.com/user-attachments/assets/9aa8a1f1-a724-4dde-8841-5d9080b6f206)

**Comment by PneumonoIsNotAvailable** [comment]
Version 1.0.8 should fix this issue, so if you haven't already updated then you should go do so. If you're running 1.0.8 already, please say so and we can reopen the issue!

**Comment by CaioMS2000** [comment]
> Version 1.0.8 should fix this issue, so if you haven't already updated then you should go do so. If you're running 1.0.8 already, please say so and we can reopen the issue!

Done! I was using version 1.0.6 and didn't know about the update. Now it works fine. Thank you.
