### ISSUE TITLE
Dunno if this is a glitch but...

### ISSUE THREAD

**Issue by HacoKavanah** [PneumonoIsNotAvailable/Gravestones#13]
I right clicked my grave and then simultaneously got my flint and steel from that grave to the slot i was clicking with, setting myself on fire and almost dying again:D it was a fast action so dunno if i accidentally clicked two times but nevertheless a funny story

**Comment by PneumonoIsNotAvailable** [comment]
I went and tested to be sure, and yes, it was most likely just an accidental double-click!
