### ISSUE TITLE
give gravestone items through commands

### ISSUE THREAD

**Issue by spaghettube** [PneumonoIsNotAvailable/Gravestones#14]
hey, i saw another issue saying how they got softlocked with your mod and the same has happened on my server so i plan to switch mods as you suggested. however i would still like to give the players who lost their items, their items, before i switch. can i do that?
[crash-2024-07-24_19.34.40-client.txt](https://github.com/user-attachments/files/16366331/crash-2024-07-24_19.34.40-client.txt)

**Comment by PneumonoIsNotAvailable** [comment]
The other issue you mentioned has a version of 1.0.4 that removes the text rendering on gravestones for this purpose :D

**Comment by PneumonoIsNotAvailable** [comment]
Actually hang on I can just release the 1.20.1 backport I made for a friend, god damn ADHD how did I not think of doing that when I actually made it

**Comment by PneumonoIsNotAvailable** [comment]
Released!
