### ISSUE TITLE
Gravestone Owner Null Error Crashing Player Session on Server

### ISSUE THREAD

**Issue by StitchLockwood** [PneumonoIsNotAvailable/Gravestones#15]
There's an issue where a gravestone is causing players who venture too close to it to crash out of the server.  It appears to be an issue where the gravestone owner is listed as "null"

I replaced the block and now it seems fine, but I wanted to bring this issue to your attention in case there was something you could add into the mod to help prevent this issue in the future.  I can provide the crash report if you need that. (will check back on this message in about a week for a reply if you do need it)

**Comment by PneumonoIsNotAvailable** [comment]
If the server is running on 1.20.1, this is a known issue. There's an update available now that fixes it (originally I said I wouldn't backport, but a friend wanted to run a server with Gravestones).

If the server is running on 1.21, this is probably a new issue and yes the crash report is needed! Reply again and we can re-open the issue.

**Comment by StitchLockwood** [comment]
Yes, server is on 1.20.1. I actually found this mod by looking at the modlist for "The Pond."  I have attached multiple crash reports for you.  Not 100% sure if this is the cause but most of them seem to happen when a gravestone is in the water.
[crash-2024-07-24_20.15.42-client.txt](https://github.com/user-attachments/files/16368703/crash-2024-07-24_20.15.42-client.txt)
[crash-2024-07-24_20.11.16-client.txt](https://github.com/user-attachments/files/16368704/crash-2024-07-24_20.11.16-client.txt)
[crash-2024-07-24_16.52.58-client.txt](https://github.com/user-attachments/files/16368709/crash-2024-07-24_16.52.58-client.txt)

**Comment by PneumonoIsNotAvailable** [comment]
There's an update on modrinth that fixes it [here](https://modrinth.com/mod/pneumono_gravestones/version/1.0.8-1.20.1). The water is actually just a coincidence, it's caused by logging off and logging back on again, because I messed up properly storing the NBT data of the gravestones.
