### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by masuteri** [PneumonoIsNotAvailable/Gravestones#19]
What do the different configurations do? Like what other options are there other than "REAL_TIME" for the decay. What unit is the decay time in? Ticks? Seconds? I'm also really asking.

**Comment by PneumonoIsNotAvailable** [comment]
There's the [Wiki](https://github.com/PneumonoIsNotAvailable/Gravestones/wiki), which explains all the configs in more detail, but it is lacking explanation for how things work if you're manually editing the config file, so I'll add that now.

For now, the only option for the decay time type is `TICKS`, and the decay time uses ticks as a measurement.

**Comment by PneumonoIsNotAvailable** [comment]
Added an explanation of accepted values and units to the Wiki for any configs that aren't simply `true`/`false`.
