### ISSUE TITLE
Mod not working correctly with trinkets

### ISSUE THREAD

**Issue by Fabsian10000** [PneumonoIsNotAvailable/Gravestones#2]
im using the mod trinkets alongside the gravestone mod, but whenever i die all the items i have equiped in the trinkets slots stay equipped, its neat to have some stuff still after death but im sure it shouldnt be like that

**Comment by PneumonoIsNotAvailable** [comment]
Coincidentally that should be fixed thanks to something else (proper trinkets support) thats ready for the next update, which I'll release properly soon. There's a few other things I want to change before releasing it but it shouldn't be too long!

**Comment by Fabsian10000** [comment]
Oh thats a nice coincidence! Looking forward to the update! Love your mod and its style! It fits very nicely into the vanilla style/artstyle!

**Comment by PneumonoIsNotAvailable** [comment]
Thank you!

**Comment by PneumonoIsNotAvailable** [comment]
Update released!
