### ISSUE TITLE
When doing a failed waterdrop the gravestone disappeared

### ISSUE THREAD

**Issue by ru72** [PneumonoIsNotAvailable/Gravestones#21]
I died with the options that allow the gravestones to break off and when I went to my death location the gravestone wasn't there, I think that where should be an ubituary where your inventory would be saved just before you die and a button to make the gravestone respawn. Thanks for reading and for making this awesome mod!

**Comment by PneumonoIsNotAvailable** [comment]
Could you provide some more info on what happened when you died? Did you see the gravestone appear then it was gone when you got back?
Some kind of inventory backup feature is probably a good idea, in case there are more issues.

**Comment by ru72** [comment]
The gravestone appeared and then it was replaced by the water, the
coordinates of where the grave should have been were correct but it was
missing. Thaks for your work.
