### ISSUE TITLE
New mixin somehow breaking gravestone functionality

### ISSUE THREAD

**Issue by Com2486** [PneumonoIsNotAvailable/Gravestones#26]
Uhh, yeah it's me again

The new update (1.0.10-1.20.1) seems to break the gravestone's item holding functionality. On death, the items spew out everywhere, but the gravestones are there and still seem to store XP.
Funnily enough, the previous explosion bug, #25, *IS* fixed, but it broke the main feature of the mod. Oops.

(This was tested on an extended modpack and one with only Gravestones and Pneumonocore.)

**Comment by Com2486** [comment]
https://github.com/user-attachments/assets/a09202f3-0588-4d4c-bbb6-df284b4f5bd6

**Comment by PneumonoIsNotAvailable** [comment]
shit

**Comment by PneumonoIsNotAvailable** [comment]
Turns out it wasn't the mixin, I just made more changes than I remembered since I last touched the mod and I forgot some of them were unfinished/untested...

_Hopefully_ [this](https://modrinth.com/mod/pneumono_gravestones/version/1.0.11-1.20.1) version is the last one I need to make today lmao
