### ISSUE TITLE
1.21 support?

### ISSUE THREAD

**Issue by rwagner76** [PneumonoIsNotAvailable/Gravestones#5]
Feel free to delete if there's no interest.

I'm getting ready to start a new server on 1.21 as soon as a couple other mods are available.  Some of our players asked specifically for the features this mod has (chance of losing items, reverting to vanilla, etc).  Any chance you'd be able to provide a build for 1.21?

**Comment by PneumonoIsNotAvailable** [comment]
Sure! I was planning on updating everything soon anyway, I just hadn't gotten around to it yet, but I can start working on it now!

**Comment by rwagner76** [comment]
Spectacular, thanks!!!

**Comment by PneumonoIsNotAvailable** [comment]
Should be uploaded now!
