### ISSUE TITLE
Creeper explosion causes crash

### ISSUE THREAD

**Issue by Artoriandaraisin** [PneumonoIsNotAvailable/Gravestones#6]
When a creeper explodes, specifically with the 1.21 version of this mod, the game crashes. This can be done both in creative and survival. Simply install the mod, fabric api, and pneumonocore, and creepers cause crashes. Just the dependencies will not do this. Link to the crash log in a clean modrinth instance: [crash](https://pastebin.com/RUJ394zq)

**Comment by PneumonoIsNotAvailable** [comment]
Should be fixed! Sorry!
