### ISSUE TITLE
Gravestones crash

### ISSUE THREAD

**Issue by HacoKavanah** [PneumonoIsNotAvailable/Gravestones#7]
[crash-2024-06-27_16.23.00-server.txt](https://github.com/user-attachments/files/16014717/crash-2024-06-27_16.23.00-server.txt)
My friend got this crash when he died in our modded world.

**Comment by PneumonoIsNotAvailable** [comment]
What was the situation in which he died? From what I can tell, he died surrounded by blocks the gravestone didn't want to replace (likely block entities or strong/unbreakable blocks), but if this isn't the case it's probably a larger issue I need to investigate further

**Comment by HacoKavanah** [comment]
Thank you for the quick answer!

According to him, he was in a trial chamber.

**Comment by PneumonoIsNotAvailable** [comment]
I'm not completely sure how this was caused in a trial chamber, but either way it should be fixed now! (1.0.7 on Modrinth)
