### ISSUE TITLE
Graves not storing XP

### ISSUE THREAD

**Issue by Nalyd217** [PneumonoIsNotAvailable/Gravestones#8]
In the config, I have the option for storing XP set to true. However when I die in game, my experience does not come back when claiming the grave. Decay has also been disabled. This is happening in a fabric multiplayer world.

**Comment by PneumonoIsNotAvailable** [comment]
I can't recreate this, do you have any other mods installed that might cause this?

**Comment by Nalyd217** [comment]
Client side mods:
![image](https://github.com/PneumonoIsNotAvailable/Gravestones/assets/63613933/1f88db34-f6a5-4697-90c9-9ba7439d34ef)

Server side mods:
![image](https://github.com/PneumonoIsNotAvailable/Gravestones/assets/63613933/19b36b5d-1180-4600-8280-688ad370220b)

It was happening before the mods that were installed today (July 4), and it was happening on the previous version of the gravestones mod. I updated that today bc the game would crash when dying in lava, and I saw that was fixed. 

Just to confirm, if I want all xp to be stored in the grave, is this what the config should look like? The screenshot if from the server side config. Client config is the same way. 
![image](https://github.com/PneumonoIsNotAvailable/Gravestones/assets/63613933/272dba2a-76b8-4588-b87d-3d2794b72834)

Please let me know if you need additional information.

**Comment by PneumonoIsNotAvailable** [comment]
I honestly have no idea what could be causing this. The config looks fine, but just to be clear there is still the 7-and-a-bit levels XP cap after dying, like with vanilla deaths (now that I mention it I should probably add a config to disable that)

**Comment by Nalyd217** [comment]
...lmao my bad, yes that's exactly what's happening. I didn't realize that was intentional. I just saw "no xp decay" in the config and thought that meant I would get all my xp back. So I guess this is resolved, but like you mentioned, that would be a nice config option!

**Comment by PneumonoIsNotAvailable** [comment]
Oh, no worries!
