### ISSUE TITLE
my grave saying i can’t access it

### ISSUE THREAD

**Issue by axe2789** [PneumonoIsNotAvailable/Gravestones#9]
i died and my game crashed on my way to my grave on my server, i got to it and it says i can’t access it only the owner and then my username can access it but it won’t allow me

**Comment by axe2789** [comment]
also i can’t figure out how to make graves available to access by anyone

**Comment by PneumonoIsNotAvailable** [comment]
I can't think of anything that might cause the access issue, unless maybe if you're using a cracked client? Was the crash related to gravestones at all?

Making graves accessible to everyone should be as simple as setting `gravestone_accessible_owner_only` to `false` in the configs. If this is a multiplayer server, make sure to do this serverside (clients should sync any configs that are serverside)

**Comment by axe2789** [comment]
crash was because of changing shaders as my laptop isn’t that great, not using a cracked client, thank you, i’ll look at trying to change that later :)

**Comment by PneumonoIsNotAvailable** [comment]
Tested it out and I've managed to recreate this! I'll get it fixed soon. In the meantime, creative mode players can break any grave and it will drop the contents, so if you have access to cheats you can get your stuff back without having to wait for me to update the mod.

**Comment by ThatOneCodeDev** [comment]
Can confirm as well, I have one player who is affected by this issue on my server. The creative workaround worked like a charm. 🙏

**Comment by axe2789** [comment]
since making that comment yesterday i also died in the nether with no crashed or anything and got back yo my stuff in less than a minute with it still telling me i wasn’t able to access my stuff

**Comment by PneumonoIsNotAvailable** [comment]
Did you leave the world and rejoin at all? This seems to happen whenever someone disconnects and reconnects, not just with crashes. (If so it should be fixed once I release the next update, but it's better to be sure)

**Comment by axe2789** [comment]
the time of dying in the nether i had not left the world at all

**Comment by PneumonoIsNotAvailable** [comment]
I can't recreate that, but I'm fairly sure if it's still saying the grave is yours, it's a side effect of this issue. More specifically, I'm just really stupid and didn't understand how to properly compare UUIDs, so the saved UUID of the gravestone would sometimes not appear equal to the UUID of the player. If it's saved your name, it's most likely also saved your UUID, so it should just be this again.

**Comment by PneumonoIsNotAvailable** [comment]
[Update released!](https://modrinth.com/mod/pneumono_gravestones/version/1.0.8)

**Comment by axe2789** [comment]
awesome! i’ll update my server with friends soon! :)
